name: "Docker"

on:
  workflow_dispatch:

  push:

  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: read

jobs:
  build:
    name: "Build"
    uses: dockette/.github/.github/workflows/docker.yml@master
    secrets: inherit
    with:
      image: "dockette/coder"
      tag: "fx"
      context: "fx"
      platforms: "linux/amd64"
      push: ${{ github.ref == 'refs/heads/master' }}
